# Generated by Django 4.1 on 2022-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('countryCode', models.CharField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('groupId', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
