# Generated by Django 4.1 on 2022-08-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_API', '0002_alter_countries_createdat_alter_countries_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='groupId',
        ),
    ]
